keepalived_router_id: WN1_VIP

keepalived_instances:
  - name: VI_INGRESS
    interface: ens160
    vrid: 200
    priority: 100
    advert_int: 1
    auth_pass: ingvip01
    vip: 10.2.2.101/24

  - name: API_VIP
    interface: ens160
    vrid: 53
    priority: 150
    advert_int: 1
    auth_pass: apivip02
    vip: 10.2.2.253/24
